/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Iuran = IDL.Record({
  'id' : IDL.Nat,
  'jumlah' : IDL.Nat,
  'tahun' : IDL.Nat,
  'kkId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'tanggalBayar' : IDL.Text,
  'keterangan' : IDL.Text,
  'bulan' : IDL.Nat,
  'statusLunas' : IDL.Bool,
});
export const KK = IDL.Record({
  'id' : IDL.Nat,
  'namaKepala' : IDL.Text,
  'blokRumah' : IDL.Text,
  'alamat' : IDL.Text,
  'noHP' : IDL.Text,
  'createdAt' : IDL.Int,
  'nomorKK' : IDL.Text,
});
export const Warga = IDL.Record({
  'id' : IDL.Nat,
  'nik' : IDL.Text,
  'namaLengkap' : IDL.Text,
  'tanggalLahir' : IDL.Text,
  'tempatLahir' : IDL.Text,
  'kkId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'statusAktif' : IDL.Bool,
  'jenisKelamin' : IDL.Text,
  'hubunganKK' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createIuran' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createKK' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createWarga' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteIuran' : IDL.Func([IDL.Nat], [], []),
  'deleteKK' : IDL.Func([IDL.Nat], [], []),
  'deleteWarga' : IDL.Func([IDL.Nat], [], []),
  'getAdminUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllIuran' : IDL.Func([], [IDL.Vec(Iuran)], ['query']),
  'getAllKK' : IDL.Func([], [IDL.Vec(KK)], ['query']),
  'getAllWarga' : IDL.Func([], [IDL.Vec(Warga)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIuranByBulanTahun' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Iuran)],
      ['query'],
    ),
  'getIuranById' : IDL.Func([IDL.Nat], [Iuran], ['query']),
  'getIuranByKKId' : IDL.Func([IDL.Nat], [IDL.Vec(Iuran)], ['query']),
  'getJumlahBelumLunas' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getJumlahLunas' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getKKById' : IDL.Func([IDL.Nat], [KK], ['query']),
  'getTotalIuranTerkumpul' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getTotalKK' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalWarga' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWargaById' : IDL.Func([IDL.Nat], [Warga], ['query']),
  'getWargaByKKId' : IDL.Func([IDL.Nat], [IDL.Vec(Warga)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'logoutSession' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateIuran' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateKK' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateWarga' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Iuran = IDL.Record({
    'id' : IDL.Nat,
    'jumlah' : IDL.Nat,
    'tahun' : IDL.Nat,
    'kkId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'tanggalBayar' : IDL.Text,
    'keterangan' : IDL.Text,
    'bulan' : IDL.Nat,
    'statusLunas' : IDL.Bool,
  });
  const KK = IDL.Record({
    'id' : IDL.Nat,
    'namaKepala' : IDL.Text,
    'blokRumah' : IDL.Text,
    'alamat' : IDL.Text,
    'noHP' : IDL.Text,
    'createdAt' : IDL.Int,
    'nomorKK' : IDL.Text,
  });
  const Warga = IDL.Record({
    'id' : IDL.Nat,
    'nik' : IDL.Text,
    'namaLengkap' : IDL.Text,
    'tanggalLahir' : IDL.Text,
    'tempatLahir' : IDL.Text,
    'kkId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'statusAktif' : IDL.Bool,
    'jenisKelamin' : IDL.Text,
    'hubunganKK' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createIuran' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createKK' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createWarga' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteIuran' : IDL.Func([IDL.Nat], [], []),
    'deleteKK' : IDL.Func([IDL.Nat], [], []),
    'deleteWarga' : IDL.Func([IDL.Nat], [], []),
    'getAdminUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllIuran' : IDL.Func([], [IDL.Vec(Iuran)], ['query']),
    'getAllKK' : IDL.Func([], [IDL.Vec(KK)], ['query']),
    'getAllWarga' : IDL.Func([], [IDL.Vec(Warga)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIuranByBulanTahun' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Iuran)],
        ['query'],
      ),
    'getIuranById' : IDL.Func([IDL.Nat], [Iuran], ['query']),
    'getIuranByKKId' : IDL.Func([IDL.Nat], [IDL.Vec(Iuran)], ['query']),
    'getJumlahBelumLunas' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getJumlahLunas' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getKKById' : IDL.Func([IDL.Nat], [KK], ['query']),
    'getTotalIuranTerkumpul' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getTotalKK' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalWarga' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWargaById' : IDL.Func([IDL.Nat], [Warga], ['query']),
    'getWargaByKKId' : IDL.Func([IDL.Nat], [IDL.Vec(Warga)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'logoutSession' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateIuran' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateKK' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateWarga' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };