/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Iuran {
  'id' : bigint,
  'jumlah' : bigint,
  'tahun' : bigint,
  'kkId' : bigint,
  'createdAt' : bigint,
  'tanggalBayar' : string,
  'keterangan' : string,
  'bulan' : bigint,
  'statusLunas' : boolean,
}
export interface KK {
  'id' : bigint,
  'namaKepala' : string,
  'blokRumah' : string,
  'alamat' : string,
  'noHP' : string,
  'createdAt' : bigint,
  'nomorKK' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Warga {
  'id' : bigint,
  'nik' : string,
  'namaLengkap' : string,
  'tanggalLahir' : string,
  'tempatLahir' : string,
  'kkId' : bigint,
  'createdAt' : bigint,
  'statusAktif' : boolean,
  'jenisKelamin' : string,
  'hubunganKK' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createIuran' : ActorMethod<
    [bigint, bigint, bigint, bigint, boolean, string, string],
    bigint
  >,
  'createKK' : ActorMethod<[string, string, string, string, string], bigint>,
  'createWarga' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean],
    bigint
  >,
  'deleteIuran' : ActorMethod<[bigint], undefined>,
  'deleteKK' : ActorMethod<[bigint], undefined>,
  'deleteWarga' : ActorMethod<[bigint], undefined>,
  'getAdminUsername' : ActorMethod<[], [] | [string]>,
  'getAllIuran' : ActorMethod<[], Array<Iuran>>,
  'getAllKK' : ActorMethod<[], Array<KK>>,
  'getAllWarga' : ActorMethod<[], Array<Warga>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIuranByBulanTahun' : ActorMethod<[bigint, bigint], Array<Iuran>>,
  'getIuranById' : ActorMethod<[bigint], Iuran>,
  'getIuranByKKId' : ActorMethod<[bigint], Array<Iuran>>,
  'getJumlahBelumLunas' : ActorMethod<[bigint, bigint], bigint>,
  'getJumlahLunas' : ActorMethod<[bigint, bigint], bigint>,
  'getKKById' : ActorMethod<[bigint], KK>,
  'getTotalIuranTerkumpul' : ActorMethod<[bigint, bigint], bigint>,
  'getTotalKK' : ActorMethod<[], bigint>,
  'getTotalWarga' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWargaById' : ActorMethod<[bigint], Warga>,
  'getWargaByKKId' : ActorMethod<[bigint], Array<Warga>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithCredentials' : ActorMethod<[string, string, string], [] | [string]>,
  'logoutSession' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminCredentials' : ActorMethod<[string, string], undefined>,
  'updateIuran' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, boolean, string, string],
    undefined
  >,
  'updateKK' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateWarga' : ActorMethod<
    [bigint, bigint, string, string, string, string, string, string, boolean],
    undefined
  >,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];