/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Iuran {
    id: bigint;
    jumlah: bigint;
    tahun: bigint;
    kkId: bigint;
    createdAt: bigint;
    tanggalBayar: string;
    keterangan: string;
    bulan: bigint;
    statusLunas: boolean;
}
export interface Warga {
    id: bigint;
    nik: string;
    namaLengkap: string;
    tanggalLahir: string;
    tempatLahir: string;
    kkId: bigint;
    createdAt: bigint;
    statusAktif: boolean;
    jenisKelamin: string;
    hubunganKK: string;
}
export interface UserProfile {
    name: string;
}
export interface KK {
    id: bigint;
    namaKepala: string;
    blokRumah: string;
    alamat: string;
    noHP: string;
    createdAt: bigint;
    nomorKK: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createIuran(kkId: bigint, bulan: bigint, tahun: bigint, jumlah: bigint, statusLunas: boolean, tanggalBayar: string, keterangan: string): Promise<bigint>;
    createKK(nomorKK: string, namaKepala: string, alamat: string, blokRumah: string, noHP: string): Promise<bigint>;
    createWarga(kkId: bigint, nik: string, namaLengkap: string, tempatLahir: string, tanggalLahir: string, jenisKelamin: string, hubunganKK: string, statusAktif: boolean): Promise<bigint>;
    deleteIuran(id: bigint): Promise<void>;
    deleteKK(id: bigint): Promise<void>;
    deleteWarga(id: bigint): Promise<void>;
    getAdminUsername(): Promise<string | null>;
    getAllIuran(): Promise<Array<Iuran>>;
    getAllKK(): Promise<Array<KK>>;
    getAllWarga(): Promise<Array<Warga>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIuranByBulanTahun(bulan: bigint, tahun: bigint): Promise<Array<Iuran>>;
    getIuranById(id: bigint): Promise<Iuran>;
    getIuranByKKId(kkId: bigint): Promise<Array<Iuran>>;
    getJumlahBelumLunas(bulan: bigint, tahun: bigint): Promise<bigint>;
    getJumlahLunas(bulan: bigint, tahun: bigint): Promise<bigint>;
    getKKById(id: bigint): Promise<KK>;
    getTotalIuranTerkumpul(bulan: bigint, tahun: bigint): Promise<bigint>;
    getTotalKK(): Promise<bigint>;
    getTotalWarga(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWargaById(id: bigint): Promise<Warga>;
    getWargaByKKId(kkId: bigint): Promise<Array<Warga>>;
    isCallerAdmin(): Promise<boolean>;
    loginWithCredentials(username: string, passwordHash: string, token: string): Promise<string | null>;
    logoutSession(token: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminCredentials(username: string, passwordHash: string): Promise<void>;
    updateIuran(id: bigint, kkId: bigint, bulan: bigint, tahun: bigint, jumlah: bigint, statusLunas: boolean, tanggalBayar: string, keterangan: string): Promise<void>;
    updateKK(id: bigint, nomorKK: string, namaKepala: string, alamat: string, blokRumah: string, noHP: string): Promise<void>;
    updateWarga(id: bigint, kkId: bigint, nik: string, namaLengkap: string, tempatLahir: string, tanggalLahir: string, jenisKelamin: string, hubunganKK: string, statusAktif: boolean): Promise<void>;
    validateSession(token: string): Promise<boolean>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createIuran(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: boolean, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIuran(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIuran(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createKK(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createKK(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKK(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createWarga(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWarga(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWarga(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteIuran(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIuran(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIuran(arg0);
            return result;
        }
    }
    async deleteKK(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKK(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKK(arg0);
            return result;
        }
    }
    async deleteWarga(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWarga(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWarga(arg0);
            return result;
        }
    }
    async getAdminUsername(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUsername();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUsername();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIuran(): Promise<Array<Iuran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIuran();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIuran();
            return result;
        }
    }
    async getAllKK(): Promise<Array<KK>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKK();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKK();
            return result;
        }
    }
    async getAllWarga(): Promise<Array<Warga>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWarga();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWarga();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIuranByBulanTahun(arg0: bigint, arg1: bigint): Promise<Array<Iuran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIuranByBulanTahun(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIuranByBulanTahun(arg0, arg1);
            return result;
        }
    }
    async getIuranById(arg0: bigint): Promise<Iuran> {
        if (this.processError) {
            try {
                const result = await this.actor.getIuranById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIuranById(arg0);
            return result;
        }
    }
    async getIuranByKKId(arg0: bigint): Promise<Array<Iuran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIuranByKKId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIuranByKKId(arg0);
            return result;
        }
    }
    async getJumlahBelumLunas(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getJumlahBelumLunas(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJumlahBelumLunas(arg0, arg1);
            return result;
        }
    }
    async getJumlahLunas(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getJumlahLunas(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJumlahLunas(arg0, arg1);
            return result;
        }
    }
    async getKKById(arg0: bigint): Promise<KK> {
        if (this.processError) {
            try {
                const result = await this.actor.getKKById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKKById(arg0);
            return result;
        }
    }
    async getTotalIuranTerkumpul(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIuranTerkumpul(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIuranTerkumpul(arg0, arg1);
            return result;
        }
    }
    async getTotalKK(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalKK();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalKK();
            return result;
        }
    }
    async getTotalWarga(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalWarga();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalWarga();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWargaById(arg0: bigint): Promise<Warga> {
        if (this.processError) {
            try {
                const result = await this.actor.getWargaById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWargaById(arg0);
            return result;
        }
    }
    async getWargaByKKId(arg0: bigint): Promise<Array<Warga>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWargaByKKId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWargaByKKId(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginWithCredentials(arg0: string, arg1: string, arg2: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithCredentials(arg0, arg1, arg2);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithCredentials(arg0, arg1, arg2);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutSession(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminCredentials(arg0, arg1);
            return result;
        }
    }
    async updateIuran(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: boolean, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIuran(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIuran(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateKK(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKK(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKK(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateWarga(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWarga(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWarga(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
